apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flag-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: flag-service-secret
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: togglemaster/flag-service
      property: DATABASE_URL
