apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      role: arn:aws:iam::762846202773:role/togglemaster-prod-external-secrets-role
