apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: analytics-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: analytics-service-secret
    creationPolicy: Owner
  data:
  - secretKey: AWS_SQS_URL
    remoteRef:
      key: togglemaster/sqs-url
      property: AWS_SQS_URL
#  dataFrom:
#  - extract:
#      key: togglemaster/analytics-service
