apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: togglemaster-analytics

resources:
  - configmap.yaml
  - external-secret.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - scaled-object.yaml
  - ingress.yaml
  - networkpolicy.yaml
