apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces
  - auth-service
  - flag-service
  - targeting-service
  - evaluation-service
  - analytics-service
  - eso
  - ingress
