apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: postgres://{{ .rds_username }}:{{ .rds_password }}@togglemaster-prod-auth-service-db.cmhac4oi49kr.us-east-1.rds.amazonaws.com:5432/auth_db
  data:
    - secretKey: MASTER_KEY
      remoteRef:
        key: togglemaster/prod/auth-service
        property: MASTER_KEY
    - secretKey: rds_username
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:762846202773:secret:rds!db-553f3f19-d9a8-4e85-9671-e9bd20574cdb-6fjhJi
        property: username
    - secretKey: rds_password
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:762846202773:secret:rds!db-553f3f19-d9a8-4e85-9671-e9bd20574cdb-6fjhJi
        property: password
