apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evaluation-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: evaluation-service-secret
    creationPolicy: Owner
  data:
  - secretKey: SERVICE_API_KEY
    remoteRef:
      key: togglemaster/evaluation-service
      property: SERVICE_API_KEY
  - secretKey: REDIS_URL
    remoteRef:
      key: togglemaster/redis-url
      property: REDIS_URL
  - secretKey: AWS_SQS_URL
    remoteRef:
      key: togglemaster/sqs-url
      property: AWS_SQS_URL
