apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd-prod
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.6
    helm:
      parameters:
      - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: arn:aws:iam::762846202773:role/togglemaster-prod-external-secrets-role
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
