apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd-prod
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.14.2
    helm:
      parameters:
      - name: serviceAccount.operator.annotations.eks\.amazonaws\.com/role-arn
        value: arn:aws:iam::762846202773:role/togglemaster-prod-keda-operator-role
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
