apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flag-service
  namespace: argocd-prod
spec:
  project: default
  source:
    repoURL: https://github.com/jobucaldas/3DCLT-TC.git
    targetRevision: main
    path: k8s/app/flag-service
  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster-flag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
