apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: targeting-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: targeting-service-secret
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: togglemaster/prod/targeting-service
      property: DATABASE_URL
