apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: targeting-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: targeting-service-secret
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: postgres://{{ .rds_username }}:{{ .rds_password }}@{{ .rds_host }}:{{ .rds_port }}/targeting_db
  data:
  - secretKey: rds_username
    remoteRef:
      key: REPLACE_ME_RDS_TARGETING_ARN
      property: username
  - secretKey: rds_password
    remoteRef:
      key: REPLACE_ME_RDS_TARGETING_ARN
      property: password
  - secretKey: rds_host
    remoteRef:
      key: REPLACE_ME_RDS_TARGETING_ARN
      property: host
  - secretKey: rds_port
    remoteRef:
      key: REPLACE_ME_RDS_TARGETING_ARN
      property: port
