apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: targeting-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: targeting-service-secret
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: postgres://{{ .rds_username }}:{{ .rds_password }}@togglemaster-prod-targeting-service-db.cmhac4oi49kr.us-east-1.rds.amazonaws.com:5432/targeting_db
  data:
    - secretKey: rds_username
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:762846202773:secret:rds!db-74577bc2-c3a4-4957-a0dc-8b43633938d8-qOiK85
        property: username
    - secretKey: rds_password
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:762846202773:secret:rds!db-74577bc2-c3a4-4957-a0dc-8b43633938d8-qOiK85
        property: password
