apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: targeting-service
spec:
  podSelector:
    matchLabels:
      app: targeting-service
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: togglemaster-evaluation
      ports:
        - protocol: TCP
          port: 8003
