apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
type: Opaque
data:
  SERVICE_API_KEY: ## API Key
  REDIS_URL: ## Redis URL
  AWS_SQS_URL: ## SQS URL
  AWS_ACCESS_KEY_ID: ## Access Key ID
  AWS_SECRET_ACCESS_KEY: ## Secret Access Key
