name: Terraform Plan

on:
  pull_request:

  workflow_call:
    inputs:
      environment:
        description: "Terraform environment to deploy to: dev or prod"
        required: false
        default: "dev"
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format
        working-directory: terraform/deployments/togglemaster
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: terraform/deployments/togglemaster
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/deployments/togglemaster
        run: terraform validate

      - name: Terraform Plan
        shell: bash
        env:
          TF_VAR_db_password: ${{ secrets.db_password }}
        working-directory: terraform/deployments/togglemaster
        run: terraform plan -var-file=terraform/deployments/togglemaster/${{ inputs.environment || 'dev' }}.tfvars -out=tfplan

      - name: Save Terraform Plan
        uses: actions/upload-artifact@v7
        with:
          name: terraform-plan
          path: tfplan
